increased max_iter to 50 and added a check for it hitting the limit (iterations stop at 49 if max_iter=50)
test now gets
Exception: ('KMeans unexpectedly took %s iterations..which was the full amount allowed by max_iter %s', (49, 50))

which I think is related to why it doesn't get to the right center with this seed.