trying some additional time formatting. the build isn't working for me, but don't think this is due to me I get this on everything: Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/IllegalFieldValueException